import random

def picture(pokemon):
    pokemon_list = ["charmander", "squirtle", "bulbasaur", "pikachu"]
    random_pokemon = random.choice(pokemon_list)
    if random_pokemon == "charmander":
        print("Charmader: \n")
        print("              _.--\"\"`-..\n")
        print("            ,'          `.\n")
        print("          ,'          __  `.\n")
        print("         /|          \" __   \\\n")
        print("        , |           / |.   .\n")
        print("        |,'          !_.'|   |\n")
        print("      ,'             '   |   |\n")
        print("     /              |`--'|   |\n")
        print("    |                `---'   |\n")
        print("     .   ,                   |                       ,\".\n")
        print("      ._     '           _'  |                    , ' \\ `\n")
        print("  `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,|\n")
        print("  |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\\n")
        print("-:..     `. `-..--_.,.<       `\"      / `.        `-/ |   .\n")
        print("  `,         \"\"\"\"'     `.              ,'         |   |  ',,\n")
        print("    `.      '            '            /          '    |'. |/\n")
        print("      `.   |              \\       _,-'           |       ''\n")
        print("        `._'               \\   '\"\\                .      |\n")
        print("           |                '     \\                `._  ,'\n")
        print("           |                 '     \\                 .'|\n")
        print("           |                 .      \\                | |\n")
        print("           |                 |       L              ,' |\n")
        print("           `                 |       |             /   '\n")
        print("            \\                |       |           ,'   /\n")
        print("          ,' \\               |  _.._ ,-..___,..-'    ,'\n")
        print("         /     .             .      `!             ,j'\n")
        print("        /       `.          /        .           .'/\n")
        print("       .          `.       /         |        _.'.'\n")
        print("        `.          7`'---'          |------\"'_.'\n")
        print("       _,.`,_     _'                ,''-----\"'\n")
        print("   _,-_    '       `.     .'      ,\\\n")
        print("   -\" /`.         _,'     | _  _  _.|\n")
        print("    \"\"--'---\"\"\"\"\"'        `' '! |! /\n")
        print("                            `\" \" -'\n")
    elif random_pokemon == "squirtle":
        print("Squirtle: \n")
        print("               _,........__\n")
        print("            ,-'            \"`-.\n")
        print("          ,'                   `-.\n")
        print("        ,'                        \\\n")
        print("      ,'                           .\n")
        print("      .'\\               ,\"\".       `\n")
        print("     ._.'|             / |  `       \\\n")
        print("     |   |            `-.'  ||       `.\n")
        print("     |   |            '-._,'||       | \\\n")
        print("     .`.,'             `..,'.'       , |`-.\n")
        print("     l                       .'`.  _/  |   `.\n")
        print("     `-.._'-   ,          _ _'   -\" \\  .     `\n")
        print("`.\"\"\"\"\"'-.`-...,---------','         `. `....__.\n")
        print(".'        `\"-..___      __,'\\          \\  \\     \\\n")
        print("\\_ .          |   `\"\"\"\"'    `.           . \\     \\\n")
        print("  `.          |              `.          |  .     L\n")
        print("    `.        |`--...________.'.        j   |     |\n")
        print("      `._    .'      |          `.     .|   ,     |\n")
        print("         `--,\\       .            `7\"\"' |  ,      |\n")
        print("            ` `      `            /     |  |      |    _,-'\"\"\"`-.\n")
        print("             \\ `.     .          /      |  '      |  ,'          `.\n")
        print("              \\  v.__  .        '       .   \\    /| /              \\\n")
        print("               \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                |\n")
        print("                `        .        `._ ___,j.  `/ .-       ,---.     |\n")
        print("                ,`-.      \\         .\"     `.  |/        j     `    |\n")
        print("               /    `.     \\       /         \\ /         |     /    j\n")
        print("              |       `-.   7-.._ .          |\"          '         /\n")
        print("              |          `./_    `|          |            .     _,'\n")
        print("              `.           / `----|          |-............`---'\n")
        print("                \\          \\      |          |\n")
        print("               ,'           )     `.         |\n")
        print("                7____,,..--'      /          |\n")
        print("                                  `---.__,--.'\n")
    elif random_pokemon == "bulbasaur":
        print("Bulbasaur: \n")
        print("                                           /\n")
        print("                        _,.------....___,.' ',.-.\n")
        print("                     ,-'          _,.--\"        |\n")
        print("                   ,'         _.-'              .\n")
        print("                  /   ,     ,'                   `\n")
        print("                 .   /     /                     ``.\n")
        print("                 |  |     .                       \\.\\\n")
        print("       ____      |___._.  |       __               \\ `.\n")
        print("     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\\n")
        print("    .  ,            __               `              |   .\n")
        print("    `,'         ,-\"'  .               \\             |    L\n")
        print("   ,'          '    _.'                -._          /    |\n")
        print("  ,`-.    ,\".   `--'                      >.      ,'     |\n")
        print(" . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'\n")
        print(" ||:, .           ,'     /  / \\ `        `.    .      .'/\n")
        print(" j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /\n")
        print("/ L:_  |                 .  \"' :_                 `.'.'\n")
        print(".    \"\"'                  \"\"\"\"\"'                    V\n")
        print(" `.                                 .    `.   _,..  `\n")
        print("   `,_   .    .                _,-'/    .. `,'   __  `\n")
        print("    ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  .\n")
        print("   /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |\n")
        print("  .   _  `\"\"'--.._____..--\"   ,             '         |\n")
        print("  | .\" `. `-.                /-.           /          ,\n")
        print("  | `._.'    `,_               /         ,'          .\n")
        print(" .'          /| `-.        . ,'         ,           ,\n")
        print(" '-.__ __ _,','    '`-..___ -...__   ,.'\\ ____.___.'\n")
        print(" `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--'\n")
    elif pokemon.lower() == "pikachu":
        print("Pikachu: \n")
        print("                                             ,-.\n")
        print("                                          _.|  '\n")
        print("                                        .'  | /\n")
        print("                                      ,'    |'\n")
        print("                                     /      /\n")
        print("                       _..----\"\"---.'      /\n")
        print(" _.....---------...,-\"\"                  ,'\n")
        print(" `-._  \\                                /\n")
        print("     `-.+_            __           ,--. .\n")
        print("          `-.._     .:  ).        (`--\"| \\\n")
        print("               7    | `\" |         `...'  \\\n")
        print("               |     `--'     '+\"        ,\". ,\"\"-\n")
        print("               |   _...        .____     | |/    '\n")
        print("          _.   |  .    `.  '--\"   /      `./     j\n")
        print("         \\' `-.|  '     |   `.   /        /     /\n")
        print("         '     `-. `---\"      `-\"        /     /\n")
        print("          \\       `.                  _,'     /\n")
        print("           \\        `                        .\n")
        print("            \\                                j\n")
        print("             \\                              /\n")
        print("              `.                           .\n")
        print("                +                          \\\n")
        print("                |                           L\n")
        print("                |                           |\n")
        print("                |  _ /,                     |\n")
        print("                | | L)'..                   |\n")
        print("                | .    | `                  |\n")
        print("                '  \\'   L                   '\n")
        print("                 \\  \\   |                  j\n")
        print("                  `. `__'                 /\n")
        print("                _,.--.---........__      /\n")
        print("               ---.,'---`         |   -j\"\n")
        print("                .-'  '....__      L    |\n")
        print("              \"\"--..    _,-'       \\ l||\n")
        print("                  ,-'  .....------. `||'\n")
        print("               _,'                /\n")
        print("             ,'                  /\n")
        print("            '---------+-        /\n")
        print("                     /         /\n")
        print("                   .'         /\n")
        print("                 .'          /\n")
        print("               ,'           /\n")
        print("             _'....----\"\"\"\"\"\n")

def evolve(pokemon):
    if pokemon.lower() == "evolve charmander":
        print("Charmeleon: \n")
        print("                      ,-'`\\\n")
        print("                  _,\"'    j\n")
        print("           __....+       /               .\n")
        print("       ,-'\"             /                 `-._.'.\n")
        print("      /                (              ,'       .'\n")
        print("     |            _.    \\             \\   ---._ `-.\n")
        print("     ,|    ,   _.'  Y    \\             `- ,'   \\   `.`.\n")
        print("     l'    \\ ,'._,\\ `.    .              /       ,--. l\n")
        print("  .,-        `._  |  |    |              \\       _   l .\n")
        print(" /              `\"--'    /              .'       ``. |  )\n")
        print(".\\    ,                 |                .        \\ `. '\n")
        print("`.                .     |                '._  __    . \\'\n")
        print("  `-..--------...'       \\                  `'  `-\"'.  \\\n")
        print("      `......___          `._                        |  \\\n")
        print("               /`            `..                     |   .\n")
        print("              /|                `-.                  |    L\n")
        print("             / |               \\   `._               .    |\n")
        print("           ,'  |,-\"-.   .       .     `.            /     |\n")
        print("         ,'    |     '   \\      |       `.         /      |\n")
        print("       ,'     /|       \\  .     |         .       /       |\n")
        print("     ,'      / |        \\  .    +          \\    ,'       .'\n")
        print("    .       .  |         \\ |     \\          \\_,'        / j\n")
        print("    |       |  L          `|      .          `        ,' '\n")
        print("    |    _. |   \\          /      |           .     .' ,'\n")
        print("    |   /  `|    \\        .       |  /        |   ,' .'\n")
        print("    |   ,-..\\     -.     ,        | /         |,.' ,'\n")
        print("    `. |___,`    /  `.   /`.       '          |  .'\n")
        print("      '-`-'     j     ` /.\"7-..../|          ,`-'\n")
        print("                |        .'  / _/_|          .\n")
        print("                `,       `\"'/\"'    \\          `.\n")
        print("                  `,       '.       `.         |\n")
        print("             __,.-'         `.        \\'       |\n")
        print("            /_,-'\\          ,'        |        _.\n")
        print("             |___.---.   ,-'        .-':,-\"`\\,' .\n")
        print("                  L,.--\"'           '-' |  ,' `-.\\\n")
        print("                                        `.'\n")
    elif pokemon.lower() == "evolve charmeleon":
        print("Charizard: \n")
        print("                 .\"-,.__\n")
        print("                 `.     `.  ,\n")
        print("              .--'  .._,'\"-' `.\n")
        print("             .    .'         `'\n")
        print("             `.   /          ,'\n")
        print("               `  '--.   ,-\"'\n")
        print("                `\"`   |  \\\n")
        print("                   -. \\, |\n")
        print("                    `--Y.'      ___.\n")
        print("                         \\     L._, \\\n")
        print("               _.,        `.   <  <\\                _\n")
        print("             ,' '           `, `.   | \\            ( `\n")
        print("          ../, `.            `  |    .\\`.           \\ \\_\n")
        print("         ,' ,..  .           _.,'    ||\\l            )  '\".\n")
        print("        , ,'   \\           ,'.-.`-._,'  |           .  _._`.\n")
        print("      ,' /      \\ \\        `' ' `--/   | \\          / /   ..\\\n")
        print("    .'  /        \\ .         |\\__ - _ ,'` `        / /     `.`.\n")
        print("    |  '          ..         `-...-\"  |  `-'      / /        . `.\n")
        print("    | /           |L__           |    |          / /          `. `.\n")
        print("   , /            .   .          |    |         / /             ` `\n")
        print("  / /          ,. ,`._ `-_       |    |  _   ,-' /               ` \\\n")
        print(" / .           \\\"`_/. `-_ \\_,.  ,'    +-' `-'  _,        ..,-.    \\`.\n")
        print(".  '         .-f    ,'   `    '.       \\__.---'     _   .'   '     \\ \\\n")
        print("' /          `.'    l     .' /          \\..      ,_|/   `.  ,'`     L`\n")
        print("|'      _.-\"\"` `.    \\ _,'  `            \\ `.___`.'\"`-.  , |   |    | \\\n")
        print("||    ,'      `. `.   '       _,...._        `  |    `/ '  |   '     .|\n")
        print("||  ,'          `.  .,.---' ,'       `.   `.. `-'  .-' /_ .'     _   ||\n")
        print("|| '              V      / /           `   | `   ,'   ,' '.    !  `. ||\n")
        print("||/            _,-------7 '              . |  `-'    l         /    `||\n")
        print(". |          ,' .-   ,' ||               | .-.        `.      .'     ||\n")
        print(" `'        ,'    `\".'    |               |    `.        '. -.'       `'\n")
        print("          /      ,'      |               |,'    \\-.._,.'/'\n")
        print("          .     /        .               .       \\    .''\n")
        print("        .`.    |         `.             /         :_,'.'\n")
        print("          \\ `...\\   _     ,'-.        .'         /_.-'\n")
        print("           `-.__ `,  `'   .  _.>----''.  _  __  /\n")
        print("                .'        /\"'          |  \"'   '_\n")
        print("               /_|.-'\\ ,\".             '.'`__'-( \\\n")
        print("                 / ,\"'\"\\,'               `/  `-.|\"\n")
    elif pokemon.lower() == "evolve squirtle":
        print("Wartortle: \n")
        print("     __                                _.--'\"7\n")
        print("    `. `--._                        ,-'_,-  ,'\n")
        print("     ,'  `-.`-.                   /' .'    ,|\n")
        print("     `.     `. `-     __...___   /  /     - j\n")
        print("       `.     `  `.-\"\"        \" .  /       /\n")
        print("         \\     /                ` /       /\n")
        print("          \\   /                         ,'\n")
        print("          '._'_               ,-'       |\n")
        print("             | \\            ,|  |   ...-'\n")
        print("             || `         ,|_|  |   | `             _..__\n")
        print("            /|| |          | |  |   |  \\  _,_    .-\"     `-.\n")
        print("           | '.-'          |_|_,' __!  | /|  |  /           \\\n")
        print("   ,-...___ .=                  ._..'  /`.| ,`,.      _,.._ |\n")
        print("  |   |,.. \\     '  `'        ____,  ,' `--','  |    /      |\n")
        print(" ,`-..'  _)  .`-..___,---'_...._/  .'      '-...'   |      /\n")
        print("'.__' \"\"'      `.,------'\"'      ,/            ,     `.._.' `.\n")
        print("  `.             | `--........,-'.            .         \\     \\\n")
        print("    `-.          .   '.,--\"\"     |           ,'\\        |      .\n")
        print("       `.       /     |          L          ,\\  .       |  .,---.\n")
        print("         `._   '      |           \\        /  .  L      | /   __ `.\n")
        print("            `-.       |            `._   ,    l   .    j |   '  `. .\n")
        print("              |       |               `\"' |  .    |   /  '      .' |\n")
        print("              |       |                   j  |    |  /  , `.__,'   |\n")
        print("              `.      L                 _.   `    j ,'-'           |\n")
        print("               |`\"---..\\._______,...,--' |   |   /|'      /        j\n")
        print("               '       |                 |   .  / |      '        /\n")
        print("                .      .              ____L   \\'  j    -',       /\n")
        print("               / `.     .          _,\"     \\   | /  ,-','      ,'\n")
        print("              /    `.  ,'`-._     /         \\  i'.,'_,'      .'\n")
        print("             .       `.      `-..'             |_,-'      _.'\n")
        print("             |         `._      |            ''/      _,-'\n")
        print("             |            '-..._\\             `__,.--'\n")
        print("            ,'           ,' `-.._`.            .\n")
        print("           `.    __      |       \"'`.          |\n")
        print("             `-\"'  `\"\"\"\"'            7         `.\n")
        print("                                    `---'--.,'\"`'\n")
    elif pokemon.lower() == "evolve wartortle":
        print("Blastoise: \n")
        print("                       _\n")
        print("            _,..-\"\"\"--' `,.-\".\n")
        print("          ,'      __.. --',  |\n")
        print("        _/   _.-\"' |    .' | |       ____\n")
        print("  ,.-\"\"'    `-\"+.._|     `.' | `-..,',--.`.\n")
        print(" |   ,.                      '    j 7    l \\__\n")
        print(" |.-'                            /| |    j||  .\n")
        print(" `.                   |         / L`.`\"\"','|\\  \\\n")
        print("   `.,----..._       ,'`\"'-.  ,'   \\ `\"\"'  | |  l\n")
        print("     Y        `-----'       v'    ,'`,.__..' |   .\n")
        print("      `.                   /     /   /     `.|   |\n")
        print("        `.                /     l   j       ,^.  |L\n")
        print("          `._            L       +. |._   .' \\|  | \\\n")
        print("            .`--...__,..-'\"\"'-._  l L  \"\"\"    |  |  \\\n")
        print("          .'  ,`-......L_       \\  \\ \\     _.'  ,'.  l\n")
        print("       ,-\"`. / ,-.---.'  `.      \\  L..--\"'  _.-^.|   l\n")
        print(" .-\"\".'\"`.  Y  `._'   '    `.     | | _,.--'\"     |   |\n")
        print("  `._'   |  |,-'|      l     `.   | |\"..          |   l\n")
        print("  ,'.    |  |`._'      |      `.  | |_,...---\"\"\"\"\"`    L\n")
        print(" /   |   j _|-' `.     L       | j ,|              |   |\n")
        print("`--,\"._,-+' /`---^..../._____,.L',' `.             |\\  |\n")
        print("   |,'      L                   |     `-.          | \\j\n")
        print("            .                    \\       `,        |  |\n")
        print("             \\                __`.Y._      -.     j   |\n")
        print("              \\           _.,'       `._     \\    |  j\n")
        print("              ,-\"`-----\"\"\"\"'           |`.    \\  7   |\n")
        print("             /  `.        '            |  \\    \\ /   |\n")
        print("            |     `      /             |   \\    Y    |\n")
        print("            |      \\    .             ,'    |   L_.-')\n")
        print("             L      `.  |            /      ]     _.-^._\n")
        print("              \\   ,'  `-7         ,-'      / |  ,'      `-._\n")
        print("             _,`._       `.   _,-'        ,',^.-            `.\n")
        print("          ,-'     v....  _.`\"',          _:'--....._______,.-'\n")
        print("        ._______./     /',,-'\"'`'--.  ,-'  `.\n")
        print("                 \"\"\"\"\"`.,'         _\\`----...'\n")
        print("                        --------\"\"'\n")
    elif pokemon.lower() == "evolve bulbasaur":
        print("Ivysaur: \n")
        print("                               ,'\"`.,./.\n")
        print("                             ,'        Y',\"..\n")
        print("                           ,'           \\  | \\\n")
        print("                          /              . |  `\n")
        print("                         /               | |   \\\n")
        print("            __          .                | |    .\n")
        print("       _   \\  `. ---.   |                | j    |\n")
        print("      / `-._\\   `Y   \\  |                |.     |\n")
        print("     _`.    ``    \\   \\ |..              '      |,-'\"\"7,....\n")
        print("     l     '-.     . , `|  | , |`. , ,  /,     ,'    '/   ,'_,.-.\n")
        print("     `-..     `-.  : :     |/ `   ' \"\\,' | _  /          '-'    /___\n")
        print("      \\\"\"' __.,.-`.: :        /   /._    l'.,'\n")
        print("       `--,   _.-' `\".           /__ `'-.' '         .\n")
        print("       ,---..._,.--\"\"\"\"\"\"\"--.__..----,-.'   .  /    .'   ,.--\n")
        print("       |                          ,':| /    | /      .,-'--      ,.-\n")
        print("       |     .---.              .'  :|'     |/ ,.-='\"-.`\"`' _   -.'\n")
        print("       /    \\    /               `. :|--.  _L,\"---.._        \"----'\n")
        print("     ,' `.   \\ ,'           _,     `''   ``.-'       `-  -..___,'\n")
        print("    . ,.  .   `   __     .-'  _.-           `.     .__    \\\n")
        print("    |. |`        \"      !   ,.  |             `.    `.`'---'\n")
        print("    ,| |C\\       ` /    | ,' |(]|            -. |-..--`\n")
        print("   /  \"'--'       '      /___|__]        `.  `- |`.\n")
        print("  .       ,'                   ,   /       .    `. \\\n")
        print("    \\                      .,-'  ,'         .     `-.\n")
        print("     x---..`.  -'  __..--'\"/\"\"\"\"\"  ,-.      |   |   |\n")
        print("    / \\--._'-.,.--'     _`-    _. ' /       |     -.|\n")
        print("   ,   .   `-..__ ...--'  _,.-' | `   ,.-.      /  '|\n")
        print("  .  _,'         '\"-----\"\"      |    `   | /  ,'     \n")
        print("  |-'  .-.    `._               |     `._// ,'     /\n")
        print(" _|    `-'   _,' \"`--.._________|        `,'    _ /.\n")
        print("//\\   ,-._.'\"/\\__,.   _,\"     /_\\__/`. /'.-.'.-/_,`-'\n")
        print("`-\"`\"' v'    `\"  `-`-\"              `-'`-`  `'\n")
    elif pokemon.lower() == "evolve ivysaur":
        print("Venusaur: \n")
        print("                           _._       _,._\n")
        print("                        _.'   `. ' .'   _`.\n")
        print("                ,\"\"\"/`\"\"-.-.,/. ` V'\\-,`.,--/\"\"\".\"-..\n")
        print("              ,'    `...,' . ,\\-----._|     `.   /   \\\n")
        print("             `.            .`  -'`\"\" .._   :> `-'   `.\n")
        print("            ,'  ,-.  _,.-'| `..___ ,'   |'-..__   .._ L\n")
        print("           .    \\_ -'   `-'     ..      `.-' `.`-.'_ .|\n")
        print("           |   ,',-,--..  ,--../  `.  .-.    , `-.  ``.\n")
        print("           `.,' ,  |   |  `.  /'/,,.\\/  |    \\|   |\n")
        print("                `  `---'    `j   .   \\  .     '   j\n")
        print("              ,__`\"        ,'|`'\\_/`.'\\'        |\\-'-, _,.\n")
        print("       .--...`-. `-`. /    '- ..      _,    /\\ ,' .--\"'  ,'\".\n")
        print("     _'-\"\"-    --  _`'-.../ __ '.'`-^,_`-\"\"\"\"---....__  ' _,-`\n")
        print("   _.----`  _..--.'        |  \"`-..-\" __|'\"'         .\"\"-. \"\"'--.._\n")
        print("  /        '    /     ,  _.+-.'  ||._'   \"\"\"\". .          `     .__\\\n")
        print(" `---    /        /  / j'       _/|..`  -. `-`\\ \\   \\  \\   `.  \\ `-..\n")
        print(",\" _.-' /    /` ./  /`_|_,-\"   ','|       `. | -'`._,   L  \\ .  `.   |\n")
        print("`\"' /  /  / ,__...-----| _.,  ,'            `|----.._`-.|' |. .` ..  .\n")
        print("   /  '| /.,/   \\--.._ `-,' ,          .  '`.'  __,., '  ''``._ \\ \\`,'\n")
        print("  /_,'---  ,     \\`._,-` \\ //  / . \\    `._,  -`,  / / _   |   `-L -\n")
        print("   /       `.     ,  ..._ ' `_/ '| |\\ `._'       '-.'   `.,'     |\n")
        print("  '         /    /  ..   `.  `./ |   `.'    ,\"\" ,.  `.    \\      |\n")
        print("   `.     ,'   ,'   | |\\  |       \"        |  ,'\\ |   \\    `    ,L\n")
        print("   /|`.  /    '     | `-| '                  /`-' |    L    `._/  \\\n")
        print("  / | .`|    |  .   `._.'                   `.__,'   .  |     |  (`\n")
        print(" '-\"\"-'_|    `. `.__,._____     .    _,        ____ ,-  j     \".-'\"'\n")
        print("        \\      `-.  \\/.    `\"--.._    _,.---'\"\"\\/  \"_,.'     /-'\n")
        print("         )        `-._ '-.        `--\"      _.-'.-\"\"        `.\n")
        print("        ./            `,. `\".._________...\"\"_.-\"`.          _j\n")
        print("       /_\\.__,\"\".   ,.'  \"`-...________.---\"     .\".   ,.  / \\\n")
        print("              \\_/\"\"\"-'                           `-'--(_,`\"`-`\n")
    elif pokemon.lower() == "evolve pikachu":
        print("Raichu: \n")
        print("                                        _,--\"\"`---...__\n")
        print("                            _.---\"\"\"\"`-'.   .-\"\"\"'`-.._`-._\n")
        print("                _,.-----.,-\"         .\". `-.           \"---`.\n")
        print("             _,' _,.-..,'__          `.'  ,-`...._      ,\"\"''`-.\n")
        print("           ,' ,-'     / (  .   ,-.       |    `.  `-._  .       `.\n")
        print("         ,',-\"       /   `\"    `\"'       '      .    _`. \\\n")
        print("       ,','       ,-'7--.                 `.__.\"|   ( ` `j\n")
        print("      '.:--.    ,'   |   .       |\\             '    `--'\n")
        print("     /.     | ,'     |   |       `'            .\n")
        print("    '       |',\".    |._,'                     `      _.--\"\"\"\"\"-._\n")
        print("'.          `-..'    `.                      ,  \\  ,-' _.-\"\"\"\"\"-. `.\n")
        print("` `                   F  -.                 /    ,' .-'          `  `\n")
        print(" \\ `                 j     `.              ,-.   . /               . `\n")
        print("    `.               |     .-`.           .  '-.  V                 . `\n")
        print("  `   `.      .      | .    \\  \\         j      \\/|                  ' .\n")
        print("   .    `.    |`.    |-.`._/`   .        |    ,'  A                  | |\n")
        print("    \\     `. F   \\   |--`  \"._  |        `-.-\"   / .                 | |\n")
        print("     \\      -'    `. |        `\"'                  |                 F '\n")
        print("      \\             `+`.                           |                / .\n")
        print("       \\              .-`                     .    j               / ,\n")
        print("        \\              \\   `.               .'    /               ' .\n")
        print("         \\       |`._   \\    `-.._        ,'    ,'              ,'.'\n")
        print("          '      |   `.  `.       `<`\"\"\"\"'    .'             _,'.'\n")
        print("           `     |     `-. `._      )   `.     .          _.'_.'\n")
        print("            `    |        `--/     /`-._  .     `.___..--'_.\"\n")
        print("             `   |          /     /._   `\"\"`.     `. _,.-\"\n")
        print("              `  |         /     /   `--.....`.     `._\n")
        print("               ` |       ,'     /              .\"\"\"\"'  `.\n")
        print("                `'      , `-..,7                `    . `.`.\n")
        print("                       .       '                 `.   \\  `v\n")
        print("                      j.  ,   /                    `.._L_.'\n")
        print("                      || .   /\n")
        print("                      `\"-'__/\n")
    else:
        print("Pokemon not found.")

def type(pokemon):
    if pokemon.lower() == "charmander type" or pokemon.lower() == "charmeleon type" or pokemon.lower() == "charizard type":
        print("Fire")
    elif pokemon.lower() == "squirtle type" or pokemon.lower() == "wartortle type" or pokemon.lower() == "blastoise type":
        print("Water")
    elif pokemon.lower() == "bulbasaur type" or pokemon.lower() == "ivysaur type" or pokemon.lower() == "venusaur type":
        print("Grass")
    elif pokemon.lower() == "pikachu type" or pokemon.lower() == "raichu type":
        print("Electric")
    else:
        print("Pokemon not found.")

def number(pokemon):
    if pokemon.lower() == "charmander number":
        print("4")
    elif pokemon.lower() == "charmeleon number":
        print("5")
    elif pokemon.lower() == "charizard number":
        print("6")
    elif pokemon.lower() == "squirtle number":
        print("7")
    elif pokemon.lower() == "wartortle number":
        print("8")
    elif pokemon.lower() == "blastoise number":
        print("9")
    elif pokemon.lower() == "bulbasaur number":
        print("1")
    elif pokemon.lower() == "ivysaur number":
        print("2")
    elif pokemon.lower() == "venusaur number":
        print("3")
    elif pokemon.lower() == "pikachu number":
        print("25")
    elif pokemon.lower() == "raichu number":
        print("26")
    else:
        print("Pokemon not found.")
